use_frameworks!

platform :ios, '9.0'

target 'ZTAlertController_Example' do
  pod 'ZTAlertController', :path => '../'

  target 'ZTAlertController_Tests' do
    inherit! :search_paths

    
  end
end
